### ISSUE TITLE
Project configs can grow too large for sync storage

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#125]
Exceeding the quota of 8K (or 20-30 project configs) will result in the following error in the background page's console:
```
QUOTA_BYTES_PER_ITEM quota exceeded
```
and no more projects can be added.

**Comment by kptdobe** [comment]
I am just facing this problem.

The first issue is that the sidekick tells me the config has been successfully added. I had to debug the extension to see the error message. This could be mitigated by informing the user to cleanup his config.
I have 28 configs and need to add 7 more! 

Workaround: remove useless configs.

**Comment by tripodsan** [comment]
but the new sidekick should fix this problem
