### ISSUE TITLE
Tell gdrive users to use google-native file formats

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#129]
Sometimes people copy `docx` and `xlsx` files into a gdrive folder and try to preview them. If a preview of a gdrive document fails and ends in `-xlsx` or `-docx`, we could tell the user that they should convert their doc/sheet to a native google format.

**Comment by tripodsan** [comment]
why `_docx` ? when I drop a document into gdrive, it remains a `.docx`, and I can even edit it:
https://drive.google.com/drive/u/0/folders/1N2zij7EMeS95cIFiRuxfjY0OxllX8my1

**Comment by rofe** [comment]
I think it should be `-docx` and `-xslx` in the path (i'll correct that in the description). 

That and a 404 would be a sign that the user is working with a Word document rather than a GDoc, right?

**Comment by tripodsan** [comment]
> That and a 404 would be a sign that the user is working with a Word document rather than a GDoc, right?

why? no, this is before the user previewed the content. but the `edit.name` contains `*.docx`

**Comment by hsaginor** [comment]
I have a possible fix here https://github.com/hsaginor/helix-sidekick/blob/a3a40610f44dc4b9618614d2751f7862755de948/src/sidekick/module.js#L899

This is not perfect because it will fail if the user decides to "fix" this by just renaming the file but not converting the document. It would be better to get mime type. But [https://admin.hlx.page/status/ doesn't return it.

**Comment by tripodsan** [comment]
> But [https://admin.hlx.page/status/ doesn't return it.

that would be easy to change....

**Comment by tripodsan** [comment]
now it's included:

```json
edit": {
  "url": "https://docs.google.com/document/d/1egQdcgi0Ysv8hqgnTljC6b7LgqKjbZw5/edit",
  "name": "test-word-document.docx",
  "contentType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "lastModified": "Fri, 16 Sep 2022 05:46:07 GMT",
  "sourceLocation": "gdrive:1egQdcgi0Ysv8hqgnTljC6b7LgqKjbZw5",
  "status": 200
},
```

or

```json
"edit": {
  "url": "https://docs.google.com/spreadsheets/d/14A8UwbsqFzB8lQm9SMOTg_DGPjl04zyq/edit",
  "name": "test-excel-sheet.xlsx",
  "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "lastModified": "Fri, 16 Sep 2022 05:46:58 GMT",
  "sourceLocation": "gdrive:14A8UwbsqFzB8lQm9SMOTg_DGPjl04zyq",
  "status": 200
},
```

**Comment by hsaginor** [comment]
I updated code at https://github.com/hsaginor/helix-sidekick/blob/d7f2039a41db7f46b23be410cfcf784d2bbe83a5/src/sidekick/module.js#L914

The isSupportedGoogleType function could be moved to utils.js. Other than that unless there are any other comments I can open a PR from my fork to parent repo.

**Comment by tripodsan** [comment]
thanks @hsaginor, a PR would be great.

**Comment by hsaginor** [comment]
PR https://github.com/adobe/helix-sidekick/pull/343

**Comment by rofe** [comment]
Thanks for your contribution @hsaginor! I commented on the PR as well.
