### ISSUE TITLE
Sidekick error for TLC Group/GSheets

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-sidekick-extension#152]
**Description**
When editing https://docs.google.com/spreadsheets/d/1ey1XktMxDVgHEo5vPWJ3FG-w1gNnViA8vQGT81KH9XE/edit?skip_itp2_check=true#gid=0 in Safari, and clicking the Sidekick bookmarklet

```
javascript:/*%20**%20Helix%20Sidekick%20Bookmarklet%20**%20*/(()%20=%3E%20%7Bconst%20c=%7B%22owner%22:%22hlxsites%22,%22repo%22:%22tlcgrp%22,%22ref%22:%22main%22%7D;const%20s=document.createElement('script');s.id='hlx-sk-app';s.src='https://www.hlx.live/tools/sidekick/app.js';s.dataset.config=JSON.stringify(c);if(document.getElementById('hlx-sk-app'))%7Bdocument.getElementById('hlx-sk-app').replaceWith(s);%7D%20else%20%7Bdocument.head.append(s);%7D%7D)();
```

I'm seeing this error on the dev console:

```
TypeError: window.HTMLTextAreaElement.initSidekick is not a function. (In 'window.HTMLTextAreaElement.initSidekick({
  project: 'TLC Group',
  host: 'www.tlcgroup.com',
  pushDownSelector: '.header > nav',
})', 'window.HTMLTextAreaElement.initSidekick' is undefined)
```

No Sidekick UI will be shown.

**Comment by rofe** [comment]
This error was caused an error in the project's sidekick config (the function name should have read `window.hlx.initSidekick`)...

Since sidekick v6, this file should no longer be used though, and the problem should be fixed.
