### ISSUE TITLE
Add Preview URLs button that lists all urls from the current folder

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#158]
In Sharepoint / Google Drive, when you are on the "directory" view - currently the Sidekick shows the "Preview" button which is not doing anything (the extension does not show up at all). 
We could leverage the Sidekick on that view to generate a list of all the preview urls from that folder as root. A dialog could show the list as links to be able to open each of them and a "Copy" button to copy the list in clipboard to be pasted in the organizer or in a spreadsheet.

**Comment by easingthemes** [comment]
It looks like that this is implemented
<img width="728" alt="Screenshot 2023-12-27 at 18 22 17" src="https://github.com/adobe/helix-sidekick-extension/assets/2750284/2f66c578-00b2-4cd7-95f6-ac672d1f208c">

**Comment by rofe** [comment]
It sort of is, yes. Albeit for the current selection only. Closing for now.
