### ISSUE TITLE
Preview Failure Error Message(s) Should be More Helpful

### ISSUE THREAD

**Issue by shsteimer** [adobe/helix-sidekick-extension#166]
**Is your feature request related to a problem? Please describe.**
When preview fails, the error message is rather generic and not particularly helpful simply saying to try again later. Specifically, the most common preview fail scenario I see is that the page is not part of the site selected, and the request returns a 404.

**Describe the solution you'd like**
Ideally, before even showing the preview button, a call could be made to check if the page is preview-able for the current selected site. If it's not, show an info message at that point prompting the user to double check the selected site, or something to that affect

**Describe alternatives you've considered**
If a pro-active check isn't possible, I think the 404 could be detected and more helpful/specific error message could be shown based on the status code of the response.

**Comment by shsteimer** [comment]
relates to: #157 

Improving the config matching makes the ideal experience for the pro-active check easier, I think.

**Comment by rofe** [comment]
#157 is now (about to be) released. Can you re-check your use case with the latest version?
