### ISSUE TITLE
Sidekick shows CMD+S save tip when reloading from .page

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-sidekick-extension#184]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/917628/202897140-e83a233f-4d1f-4659-be96-84fe8fc856d0.png">

This should only be displayed in the edit environment.

**Comment by rofe** [comment]
I thought it would be useful here as well: if you make a change in an editor tab without cmd + s and switch to a .page tab to press reload, you won't see the latest changes...

**Comment by tripodsan** [comment]
yes, but I only read `press cmd+s` (ignoring the mambo jambo about the editor) and then I got the save-page dialog of the browser.

**Comment by rofe** [comment]
OK, I can revert to the standrad "please wait..." here.

**Comment by rofe** [comment]
Fixed
