### ISSUE TITLE
As a user, I want to use the Sidekick from GitHub

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#236]
When on a GitHub project, the Sidekick allows me to "Add the Project". From there, if I want to check the project homepage, I need to type `https://main--repo...hlx.page` in my URL bar.

Requested feature: if a GH project is known by the Sidekick, I can toggle the Sidekick and hit the Preview button to go directly on the `https://main--repo...hlx.page` of this project.

cc @rofe

**Comment by rofe** [comment]
Good idea, but I think i would rather add this as a context menu item rather than popping open the sidekick on a GitHub URL.

**Comment by rofe** [comment]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1609742/218268406-5bbe9825-c6a8-494c-bc82-4d9c3852cda5.png">
