### ISSUE TITLE
Safari extension: TypeError importing a module script failed in js console (on localhost?)

### ISSUE THREAD

**Issue by alexkli** [adobe/helix-sidekick-extension#238]
### Expected Behaviour

No sidekick extension errors in JS console of webpages, especially if the sidekick is not even open.

### Actual Behaviour

_Not sure, but this might be limited to localhost URLs, e.g. the `hlx up` dev server on http://localhost:3000_

Errors from the sidekick extension code in the javascript console of web pages:

```
TypeError: importing a module script failed
content.js:22
```

It seems to have an issue importing `./utils.js`.

See screenshots attached below.

These are just a bit annoying as the mix with any errors from the actual page itself and can be confusing. And the sidekick isn't even running.

#### Steps to Reproduce

1. Install sidekick extension in Safari
2. Set it up
3. Go to localhost:3000
4. Open developer console
5. See above error

Note the sidekick itself never becomes visible here.

#### Platform and Version

Safari 16.3 on macOS 13.2

Sidekick Safari Extension 6.7.4

(hlx up is running franklin-simulator v14.20.0)

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

<img width="557" alt="bildschirm__foto_2023-01-25_um_16 55 21" src="https://user-images.githubusercontent.com/229022/214953880-3cd415c0-3da1-4dd7-9fc3-e925bc2f2d02.png">

<img width="1431" alt="bildschirm__foto_2023-01-25_um_16 56 45" src="https://user-images.githubusercontent.com/229022/214953908-2b342ed2-5455-4924-946a-47f2d529a69c.png">

**Comment by rofe** [comment]
@alexkli is this still reproducible in TestFlight?

**Comment by alexkli** [comment]
Yes, I have the `AEM Sidekick` version `6.8.5` now and same error:

<img width="728" alt="Bildschirm­foto 2023-03-20 um 10 55 05" src="https://user-images.githubusercontent.com/229022/226426021-265d0b5c-3e8e-4def-9bdb-286b8fe61ee0.png">

The root cause seems to be a 401 or other error when trying to load the `utils.js` (network tab doesn't give much more details):
<img width="1008" alt="Bildschirm­foto 2023-03-20 um 10 55 55" src="https://user-images.githubusercontent.com/229022/226426188-907efde4-9216-42a7-9e41-a0d0d10a534e.png">

**Comment by rofe** [comment]
Weird. Can you DM me the preview and GH URL where this can be reproduced?

**Comment by alexkli** [comment]
@rofe Sorry if this wasn't clear, but I see this on localhost with NON-franklin stuff (i.e. I am not runnign `hlx up`).

**Comment by rofe** [comment]
I see! I should have read the initial description more closely 😄 

1. Agreed. The `content.js` should never be injected in case there is no matching project configuration.
2. I was able to reproduce it now, also on a local Franklin dev environment. The dynamic import of `./utils.js` from the content script is failing on any `localhost` URL. Changing the `matches` array in the `web_accessible_resources` of the manifest.json from 
```json
"matches": [
  "https://*/*",
  "http://localhost:3000/*"
]
```
to 
```json
 "matches": [
        "<all_urls>"
      ]
```
seems to solve it, would be an acceptable change imo.
