### ISSUE TITLE
Intercept network requests to the admin api and add auth automatically.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-sidekick-extension#298]
**Is your feature request related to a problem? Please describe.**
If a sidekick plugin wants to make requests to the admin api, it cannot easily obtain the auth token.

**Describe the solution you'd like**
Network requests to the admin api _just work_

**Suggestion**:
use the https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/ api to intercept the requests to the admin api and inject the auth header automatically.

**Comment by auniverseaway** [comment]
💯 

This is a relatively large issue for our Franklin migration.

**Comment by rofe** [comment]
I think https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/ is a manifest v2 API.

**Comment by tripodsan** [comment]
> I think https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/ is a manifest v2 API.

ah... I think, I mixed this up with https://developer.chrome.com/docs/extensions/reference/webRequest/

**Comment by rofe** [comment]
Wait, you were actually right the first time 😁  - `webRequest` is v2, `declarativeNetRequest` is the equivalent in v3 👍

**Comment by rofe** [comment]
Correction: `webRequest` is still available in v3, will use that.

**Comment by rofe** [comment]
Re-correction: `webRequest` won't work because request blocking has been removed in v3. So `declarativeNetRequest` is the way to go after all.
