### ISSUE TITLE
Incorrect admin url path used when using bulk preview.

### ISSUE THREAD

**Issue by dylandepass** [adobe/helix-sidekick-extension#311]
**Description**
Customer is unable to preview a document from the directory listing page. The same file can be previewed from the within the document itself.

**To Reproduce**
1. open folder [dealer-network](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-volvotrucks-us/our-difference/uptime-and-connectivity/dealer-network?csf=1&web=1&e=7tg6sK)
2. select sub-nav.docx
3. press preview

Error message:
![Screenshot 2023-04-05 at 16 01 25](https://user-images.githubusercontent.com/3231084/231176667-fad338fc-c7a2-492c-bf9a-d425ba4d391e.png)

Preview request is being sent to 
`https://admin.hlx.page/preview/hlxsites/vg-volvotrucks-us/main/sub-nav`

**Expected behavior**
Preview request should be sent to 
`https://admin.hlx.page/preview/hlxsites/vg-volvotrucks-us/main/our-difference/uptime-and-connectivity/dealer-network/sub-nav`

**Comment by rofe** [comment]
Workaround: manually navigate to parent folder and back to original folder.
