### ISSUE TITLE
Unable to load local `config.json` when in devMode

### ISSUE THREAD

**Issue by dylandepass** [adobe/helix-sidekick-extension#348]
**Description**
As part of #333 we route requests to `config.json` through the admin API to support authenticated scenarios. This requires the `credentials: 'include'` property to be sent to include the auth cookies in the request to admin.

Since we set `access-control-allow-origin: *` on every request in the cli proxy we cannot include this header when in devMode (loading a local version of config.json) or else you will hit a CORS error `WildCardOriginNotAllowed`.

**To Reproduce**
1. Enable dev mode on a site in the sidekick settings
2. Try and load the sidekick

**Expected behavior**
Sidekick loads the local version of `config.json`

**Screenshots**
![Screenshot 2023-05-10 at 8 28 12 AM](https://github.com/adobe/helix-sidekick-extension/assets/3231084/00bdb8fc-9a13-46d3-8a7f-511c207bd569)

**Comment by tripodsan** [comment]
> Since we set access-control-allow-origin: * on every request in the cli proxy 

which CLI proxy? that would be wrong. we should echo the origin

**Comment by dylandepass** [comment]
@tripodsan All requests are returning `access-control-allow-origin: *` when going through the cli proxy.

https://github.com/adobe/helix-cli/blob/aef408461e2f6220594654cd4ae7ed3f6abf6140/src/server/HelixServer.js#L66

Re: dev mode, I'm talking about the `Test project configuration locally` setting in the advanced sidekick config settings. This toggles the `devMode` property in the `SidekickConfig` object. 

![Screenshot 2023-05-10 at 11 11 27 AM](https://github.com/adobe/helix-sidekick-extension/assets/3231084/23b93467-7e4d-4290-beac-7b3fffe9f0e6)

**Comment by tripodsan** [comment]
@dylandepass then we better fix it in helix-cli

**Comment by dylandepass** [comment]
@tripodsan So here is what I'm seeing, setting `credentials=omit` on fetch requests to admin does not break things with auth'd sites because the `x-auth-token` header is still passed.

See
https://github.com/adobe/helix-sidekick-extension/blob/fe1f976ce3f503137480964a904ff14cfe6822ce/src/extension/background.js#L366

With that in mind, would you still prefer to fix this in the cli? If so.. should we just exclude `access-control-allow-origin: *` on proxy requests to `/tools/sidekick/config.json` or everything?

**Comment by tripodsan** [comment]
> setting credentials=omit on fetch
yes. but this only works with the extension. for the bookmarklet, we use cookies. so you'd also need to check that.

I think having the change in helix-cli makes sense, is simple, and we don't need to change the sidekick

**Comment by rofe** [comment]
Fwiw, `devMode` is probably ok to only work with th extension. We can make the extension mandatory for developers, not necessarily for authors.
