### ISSUE TITLE
Section separators are not copied

### ISSUE THREAD

**Issue by synox** [adobe/helix-sidekick-extension#369]
**Description**
When pressing `View document source` and then `Copy`, any --- or section separators are not copied. 

**To Reproduce**
1. Go to https://main--helix-reveal--dylandepass.hlx.page/
2. Click on `View document source`
3. Click on Copy
5. paste in Word
6. See the missing section separators

**Expected behavior**
---  should also be copied

**Screenshots**
<img width="735" alt="Screenshot 2023-05-23 at 13 10 08" src="https://github.com/adobe/helix-sidekick-extension/assets/2250964/58a28c93-c085-45fa-8e0a-184cd18334b9">

<img width="1109" alt="Screenshot 2023-05-23 at 13 10 27" src="https://github.com/adobe/helix-sidekick-extension/assets/2250964/71b9882f-4328-497c-9979-5ed38e2136aa">

**Additional context**

**Comment by rofe** [comment]
@kptdobe could you look into this?
