### ISSUE TITLE
[i18n] Unsupported loc characters in file names on Failed to Publish dialog

### ISSUE THREAD

**Issue by SunSeed2** [adobe/helix-sidekick-extension#379]
**Description**
High Ascii and 2-4byte characters are not converted and rendered correctly on Failed to Publish dialog. 
Issue applied to singular, plural and mix files.

**To Reproduce**
1. Go to Google Drive
2. Add project via extension
3. Create Word and/or Excel document with name that contain localized characters
4. Select file
5. Click on Publish on extension panel

**Expected behavior**
File name displayed correctly on Failed to Publish dialog

**Actual behavior**
Loc characters is not rendered correctly on Failed to Publish dialog

**Screenshots**
![FailedToPublish_i18n_LocSymbolsInName](https://github.com/adobe/helix-sidekick-extension/assets/28156539/8f3dd7a3-3cf9-45d2-8433-2fb48f22f7e4)

**Comment by rofe** [comment]
This is working as designed: Only normalized, small latin letters, digits and hyphens are allowed in folder and file names.
