### ISSUE TITLE
[l10n] Unlocalized strings in Delete/Unpublish dialogs in Google Drive

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#393]
**Description**
Unlocalized strings on deleting/unpublishing deleted page in Google Drive

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to any Google Drive folder
3. Right Click on extension icon > Add this project
4. Select any file > Preview
5. Copy Preview URL and follow the link
6. Click "Publish"
7. Return to Google Drive folder and delete the file, do not close the tab with live preview
8. Go back to live preview > Publish
9. Click on Unpublish/Delete button

**Expected behavior**
Strings are localized:
This page no longer has a source document, unpublishing it cannot be undone!\n\nAre you sure you want to unpublish it?
This page no longer has a source document, deleting it cannot be undone!\n\nAre you sure you want to delete it?

**Additional context**
Strings are not present in Aladdin.

**Screenshots**
![delete_de](https://github.com/adobe/helix-sidekick-extension/assets/90141516/419dd3a9-8a30-4f4a-8ded-c68ded5f7b08)
![delete_fr](https://github.com/adobe/helix-sidekick-extension/assets/90141516/528e3dad-6b60-48de-b300-f2c98118e3ed)
![unpublish_de](https://github.com/adobe/helix-sidekick-extension/assets/90141516/3b6cfd18-b3da-435d-bfed-c2034c39311d)
![unpublish_fr](https://github.com/adobe/helix-sidekick-extension/assets/90141516/c836ab6b-f24c-4969-ad28-676eee9e1cc6)

**Comment by rofe** [comment]
Should be fixed with #416 as well.

**Comment by rofe** [comment]
No, it isn't

**Comment by rofe** [comment]
Actually an i18n problem, strings were hardcoded.

**Comment by vintix** [comment]
Issue is no longer reproducible, verified on 6.30.0
![delete_1](https://github.com/adobe/helix-sidekick-extension/assets/24693505/728fe615-27af-42ab-8500-c89fbfc50800)
![unpublish_1](https://github.com/adobe/helix-sidekick-extension/assets/24693505/b64296b7-7262-4b41-acdb-6a4f87da7ab1)
