### ISSUE TITLE
[l10n] Unlocalized strings in Help Topics in Google Drive

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#395]
**Description**
Unlocalized strings in Preview/Publish/Edit Help Topics in Google Drive

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to project folder in Google Drive
3. Right Click on extension icon > Add this project
4. Left click on extension icon
5. Select any file > Preview > OK
6. Copy Preview URL and follow the link, observe
7. Click Edit, observe

**Expected behavior**
Strings are localized:
This dot indicates that the preview document has been updated since the page was last published. Click the Publish button to push the latest version live.
The user dropdown lets you to sign in or out of the Sidekick. Your project administrator can define which features you are allowed to use.
First time using the Sidekick? You are currently editing a source document. Click on the dots below to learn what you can do next...
Click the Preview button to generate the preview page for this document and open it in a separate tab.
Click the Share button to share this project configuration with someone on your team.

**Additional context**
Strings are not present in Aladdin.

**Screenshots**
![help_edit](https://github.com/adobe/helix-sidekick-extension/assets/90141516/addf5a86-a38d-4cb1-b2e3-5c3aa2bd220a)
![help_edit2](https://github.com/adobe/helix-sidekick-extension/assets/90141516/2acd301b-f18e-4be9-bf26-9d0664c4c3f0)
![help_edit3](https://github.com/adobe/helix-sidekick-extension/assets/90141516/ba4622c0-81c4-410d-8408-538e3fb42b88)
![help_preview](https://github.com/adobe/helix-sidekick-extension/assets/90141516/577b1f60-3edf-4b9b-b868-aff0bc8d8b29)
![help_publish](https://github.com/adobe/helix-sidekick-extension/assets/90141516/9edff255-3144-4bf2-b243-0918348ca127)

**Comment by rofe** [comment]
All help content needs to be localized.

**Comment by makarovan** [comment]
Issue is no longer reproducible, verified on 6.2023
![2023-06-20 395 2](https://github.com/adobe/helix-sidekick-extension/assets/90141516/dc130968-0b5d-4a62-9a52-a36e7a5bb21b)
![2023-06-20 395 3](https://github.com/adobe/helix-sidekick-extension/assets/90141516/41852730-a06b-4f5e-80d3-03d85d97fb92)
![2023-06-20 395 1](https://github.com/adobe/helix-sidekick-extension/assets/90141516/a2340344-f22c-4597-ab92-92b86f252043)
