### ISSUE TITLE
[l10n] "Available help topics" checkboxes are missing in Options > User Experience

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#403]
**Description**
"Available help topics" checkboxes does not appear after installing extension with French or German browser language. They appear after changing browser language to English and back to French/German.

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Right Click on extension icon > Options > User Experience

**Expected behavior**
Checkboxes appear after extension installation in French/German.

**Screenshots**
![user experience de](https://github.com/adobe/helix-sidekick-extension/assets/90141516/8dc01779-85c7-4338-8ca6-14133dfc97ff)

**Comment by rofe** [comment]
@makarovan help topics are currently only available in English. See email thread for translation request.

**Comment by makarovan** [comment]
Issue is no longer reproducible, verified on 6.2023
![2023-06-20 403 de fixed](https://github.com/adobe/helix-sidekick-extension/assets/90141516/36bfcc16-8aa7-40db-a198-b19e0b7d024e)
![2023-06-20_403_fixed](https://github.com/adobe/helix-sidekick-extension/assets/90141516/7e8f66fb-05e0-4b6f-acd4-864dd63962fb)
