### ISSUE TITLE
Misalignment and truncation of "Franklin preview first time user experience" help topic in Preview

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#404]
**Description**
"Franklin preview first time user experience" help topic is misaligned and truncated in Preview

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to project folder in Google Drive
3. Right Click on extension icon > Add this project
4. Edit any file > Preview

**Expected behavior**
Help topic is correctly aligned and fully visible

**Screenshots**
![tooltop truncation](https://github.com/adobe/helix-sidekick-extension/assets/90141516/c868dc48-a423-4511-93a9-361d91c8fdc4)

**Comment by rofe** [comment]
Weird, seems like the sidekick itself is not visible in the preview tab at all, just the user friendly data view...

**Comment by rofe** [comment]
Cannot reproduce

**Comment by makarovan** [comment]
Reproduced the issue in Editor, but I'm not sure about precise steps.

https://github.com/adobe/helix-sidekick-extension/assets/90141516/18dcb492-c3c0-46c3-b75d-217cc342dad9

**Comment by rofe** [comment]
@makarovan In your screen recording, the sidekick toolbar doesn't even show up. Do you see any errors in the console log (F12)?

**Comment by makarovan** [comment]
@rofe 
![2023-06-30 helix 404](https://github.com/adobe/helix-sidekick-extension/assets/90141516/b5ef8fc3-caea-47b3-b91a-83f5c8db214e)

**Comment by rofe** [comment]
Thanks. Unfortunately none of that explains the weird behavior...

**Comment by makarovan** [comment]
@rofe 
Found a way to reproduce this. Works better right after extension installing:
1. Add a project
2. Edit any file
3. Until panel is loaded, double click on extension icon (sometimes twice)
Misaligned topic has a different class and style. If those are fixed, it looks ok.
![no misalignment](https://github.com/adobe/helix-sidekick-extension/assets/90141516/f80e92b1-6b5f-4283-8850-52e39e4d100a)
![misalignment](https://github.com/adobe/helix-sidekick-extension/assets/90141516/a906894f-4f5d-4f2d-a10a-73ae89151460)

**Comment by rofe** [comment]
@makarovan the problem is that in the second screenshot, the sidekick itself isn't rendered at all (is it visible in the DOM tree at the top of the body?) which explains why the alignment class `bottom-center` isn't applied.

In any case, double clicking the extension icon sounds like an edge case to me.
