### ISSUE TITLE
Missing error text in Preview in Sharepoint

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#450]
**Description**
Error text is missing if user copies Preview URLs links and follows them in Sharepoint

**To Reproduce**
1. Go to Sharepoint project folder
2. Select two documents and click "Copy Preview URLs" on extension panel
3. Paste copied text without changing in adress bar and press Enter

**Expected behavior**
Error text is present

**Screenshots**
![copy 2 preview urls missing error](https://github.com/adobe/helix-sidekick-extension/assets/90141516/5678b121-3aac-40ea-b6cb-1ead07ffc5ff)

**Comment by rofe** [comment]
Multiple URLs are copied as a line-separated list of URLs. The main purpose is to keep track of the generated preview URLs, e.g. in a spreadsheet. You can't paste them directly into the browser's address bar.
