### ISSUE TITLE
Add project option missing when navigating via folders to the respective site

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-sidekick-extension#455]
**Description**
`add project` option is missing when navigating to the respective folder of a project.

**reproduce**
- open the sharepoint site root folder
- navigate to the respective fstab root
- open sidekick menu -> `add project` is missing
- refresh browser window
- open sidekick menu -> `add project` is present

**Comment by rofe** [comment]
Looks like the `discover` service doesn't recognize the sharepoint URL in the failing case. Do you have the console log from the service worker?

cc @dominique-pfister

**Comment by dominique-pfister** [comment]
> Looks like the discover service doesn't recognize the sharepoint URL in the failing case. Do you have the console log from the service worker?
Hm, if navigating to the fstab root alone does not work, but refreshing the browser window does, I'd rather suspect that the first request for the `discover` service doesn't show the *actual* fstab root but something else...

**Comment by tripodsan** [comment]
I suspect the folder navigation is not tracked by the sidekick before it is installed...

**Comment by tripodsan** [comment]
I tried to reproduce it on https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx, but there it works. so maybe something special on the customers sharepoint

**Comment by tripodsan** [comment]
I verified on the customers sharepoint:
- the discover service returns the correct repository information, but the add-project is missing.
- switching browser tabs and back makes it work again
- navigating to the parent folder and back makes it work again

**Comment by rofe** [comment]
Right, the `onUpdated` listener gets triggered, but remains inactive because the tab's loading status is `loading` instead of the expected `complete`...
