### ISSUE TITLE
error message in console for 404 on loading config.json 

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-sidekick-extension#456]
**Description**
if a project has no sidekick config, it shows a red error in the console:

![image](https://github.com/adobe/helix-sidekick-extension/assets/917628/23ecee5b-d766-4c7d-b845-deea6c888305)

this is confusing and should probably only be a info message.

**Comment by rofe** [comment]
Not sure if `fetch` errors like that can actually be suppressed? The call is being made inside a try/catch block, but it doesn't seem to be throwing.

**Comment by tripodsan** [comment]
right, this is not possible.

workaround: hide network messages in console:

<img width="294" alt="Screenshot 2023-07-24 at 11 42 47" src="https://github.com/adobe/helix-sidekick-extension/assets/917628/28171e9b-889e-4ecd-b682-79697100a8a3">
