### ISSUE TITLE
Custom Resource Viewers in Sidekick for preview/live envs

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-sidekick-extension#457]
There are a range of use cases (eg. `.json`, fragments, resources like PDF, SVG etc.) where it might be more user friendly to allow a project to customize what's being shown, instead of the default representation (eg. built-in JSON viewer or loading the actual resource) after the user clicks "preview" in their sharepoint / gdrive.

On top of that, it would allow for extensibility for non-HTML resources for authoring workflows and checks.

A simple way of providing that would be to allow a configuration that would for example load something like `/tools/my-metadata-json-viewer.html?payload=/metadata.json` instead of directing the browser to `/metadata.json`.

**Comment by rofe** [comment]
Special views can be configured in the sidekick config as follows:
```json
{
  ...
  "specialViews": [{
    "title": "My JSON view",
    "titleI18n": {
      "de": "Meine JSON-Ansicht"
    },
    "path": "**.json",
    "viewer": "/tools/sidekick/myjson/index.html"
  }]
}
```
