### ISSUE TITLE
[l10n] Delete/unpublish dialogs has no text in all locales except en_US

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#458]
**Description**
Delete/unpublish dialogs has no text in all locales. Text appears only in en_US

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to any Google Drive folder
3. Right Click on extension icon > Add this project
4. Select any file > Preview
5. Copy Preview URL and follow the link
6. Click "Publish"
7. Return to Google Drive folder and delete the file, do not close the tab with live preview
8. Go back to live preview > Publish
9. Click on Unpublish/Delete button

**Expected behavior**
Localized text "This page no longer has a source document, unpublishing it cannot be undone!..." appears in the dialog

**Screenshots**
![en_US](https://github.com/adobe/helix-sidekick-extension/assets/90141516/761fc3fa-1bae-4af8-800c-96e685fef9bb)
![fr_FR](https://github.com/adobe/helix-sidekick-extension/assets/90141516/a7e19efa-a609-4885-82b0-826bd69636db)
![pt_BR](https://github.com/adobe/helix-sidekick-extension/assets/90141516/7ca8cf0d-88a7-4c7a-8c2e-da16888b388b)
![zh_CN](https://github.com/adobe/helix-sidekick-extension/assets/90141516/4ee62617-c96e-4e2f-9285-a61e1ed22680)

**Comment by rofe** [comment]
@makarovan this is actually a localization issue rather than an i18n one (see [this PR](https://github.com/adobe/helix-sidekick-extension/pull/447/files)). I thought newly added english strings would be scraped automatically, sent for translation and end up in a PR once translated?

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is not reproduce please observe attachment screenshot
![458_FIXED](https://github.com/adobe/helix-sidekick-extension/assets/144205585/ade0af57-da0e-4a43-98ea-2fff0595a29c)
