### ISSUE TITLE
Last entry and vertical scroll bar not reachable in sharepoint when sidekick is enabled

### ISSUE THREAD

**Issue by cziegeler** [adobe/helix-sidekick-extension#459]
**Description**
When the sidekick is enabled, the last item in a directory listed in sharepoint is not reachable anymore. Similar if there is a vertical scroll bar.
This is the bottom of a list without sidekick:
![without](https://github.com/adobe/helix-sidekick-extension/assets/3958409/6ec2712f-aecd-4643-b5ca-c760cf63f6bb)

And the same window with sidekick enabled:
![with](https://github.com/adobe/helix-sidekick-extension/assets/3958409/a3698318-0414-42dc-8ca1-7062f83e903c)

**To Reproduce**
1. Open a sharepoint folder with a long list of items
2. Enable sidekick
3. Try to reach the last item'
4. See problem

**Expected behavior**
Vertical scroll bar stays and last entry is reachable

**Additional context**
Tested with latest Chrome on windows

**Comment by rofe** [comment]
@cziegeler have you enabled "push down content" in options > UX?

**Comment by cziegeler** [comment]
@rofe yes, I have

**Comment by rofe** [comment]
I see. Well, the feature has proven troublesome in other situations as well. I think in the upcoming redesign, the goal should be to remove/reduce the need to push down content, so this feature will no longer be needed.
