### ISSUE TITLE
Consider removing `preview` `publish` buttons before sidekick config is loaded

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-sidekick-extension#479]
in situations where the config materially impacts the buttons on sidekick it may be better to not show any buttons before the config is loaded.

**Comment by rofe** [comment]
I think this is already the case: default buttons/plugins are added on `contextloaded`, which means the config has already been loaded.

@davidnuescheler do you have an example use case where it does not behave as expected?

**Comment by rofe** [comment]
This is fixed.
