### ISSUE TITLE
redirect for sidekick config.

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-sidekick-extension#481]
i think it would be great if the admin service could respond with a `301` on requests to `https://admin.hlx.page/sidekick/<owner>/<repo>/<branch>/config.json` so the sidekick config can be centralized for a set of project.

**Comment by rofe** [comment]
Where would this redirect be configured?

**Comment by davidnuescheler** [comment]
maybe we can use the same facility we have for dev mode and broaden that to `same-site` or similar.

**Comment by rofe** [comment]
Implemented in admin service.
