### ISSUE TITLE
Sidekick does not open when using the fstab mountpoint URL

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#488]
Assuming you have already configured [adobe/blog](https://github.com/adobe/blog) project

- Open https://github.com/adobe/blog/blob/main/fstab.yaml
- Navigate to the mountpoint URL (https://adobe.sharepoint.com/sites/TheBlog/Shared%20Documents/theblog)
- Try to open the Sidekick (does not load)
- In Sharepoint, click on `Documents` then `theblog` - you can open the Sidekick from here

Expected: when navigating to the mountpoint URL, you should be able to open the Sidekick.

I am 99% sure this was working before, looks like a regression.

The issue might be coming from a different angle: when using the Admin status API, the `status.edit.folders` entry gives you the mountpoint URL. When exposed to the enduser to navigate to Sharepoint (Pfizer), the Sidekick cannot be loaded.

I traced it down to https://github.com/adobe/helix-sidekick-extension/blob/main/src/extension/utils.js#L173-L177, the response is 400 in the case of the mountpoint URL. 
@tripodsan: you have introduced this function (https://github.com/adobe/helix-sidekick-extension/commit/378db0827f004df320758aba8f72c7b7fdc4486c)... any idea ?

cc @rofe

**Comment by tripodsan** [comment]
> you have introduced this function (https://github.com/adobe/helix-sidekick-extension/commit/378db0827f004df320758aba8f72c7b7fdc4486c)... any idea ?

I check what the problem is

**Comment by tripodsan** [comment]
ah, we need to clear the query params
