### ISSUE TITLE
Unlocalized strings on extension menu in pt-BR,zh-CN,zh-TW,ko-KR locale.

### ISSUE THREAD

**Issue by vintix** [adobe/helix-sidekick-extension#516]
**Description**
Unlocalized strings on extension panel in Google Drive in pt-BR,zh-CN,zh-TW,ko-KR locale.

**To Reproduce**
 1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
 3. Go to any Google Drive folder
 4. Right Click on extension icon > Add this project
 5. Select any .html file and click Preview > OK > Open URL
 6. Right Click on extension icon 

**Expected behavior**
"Remove this project","Disable this project","View document source" string is localized

**Screenshots**
![ko-KR](https://github.com/adobe/helix-sidekick-extension/assets/24693505/b208ac84-9398-4515-b527-e31dececbdad)
![pt-BR](https://github.com/adobe/helix-sidekick-extension/assets/24693505/f2d12a69-08e6-4167-9e71-3d01d4a74cde)
![zh-CN](https://github.com/adobe/helix-sidekick-extension/assets/24693505/2b30c470-dceb-48d0-8381-ccd5ed12d297)
![zh-TW](https://github.com/adobe/helix-sidekick-extension/assets/24693505/83c851e9-60cc-4ef9-8f4f-663b84da179c)

**Additional context**
Strings are localized in Aladdin

**String ID** 
1. View document source - open_view_doc_source#message
2. Disable this project - config_project_disable#message
3. Remove this project - config_project_remove#message

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Additional strings:
Add this project - config_project_add#message
Enable this project - config_project_enable#message

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is not reproduce please observe attachment screenshot
![string_Fixed_Cick_CHT](https://github.com/adobe/helix-sidekick-extension/assets/144205585/20f3a9ab-1115-444a-a41f-9fd9a328e4da)
![string_Fixed_Cick_CHS](https://github.com/adobe/helix-sidekick-extension/assets/144205585/37c69a21-d4d0-4253-b85c-87cd237b6984)
![string_Fixed_Cick_PT_BR](https://github.com/adobe/helix-sidekick-extension/assets/144205585/0c8d26dd-4ace-4dd9-b54b-15e3ac4f4a2c)
