### ISSUE TITLE
Add Asset Selector Button to Sidekick

### ISSUE THREAD

**Issue by sdmcraft** [adobe/helix-sidekick-extension#517]
**Is your feature request related to a problem? Please describe.**
Currently, the customer has to configure AEM Assets Sidekick plugin as repo level.  Ideally, for AEM customers. this is an extra step to link 2 AEM solutions (Franklin and Assets).  This process can be simplified by making AEM Assets selector natively available in the sidekick.

**Describe the solution you'd like**
The AEM Asset selector should be natively available in the sidekick. A sidekick configuration like "Show AEM Assets" can be used to control its visibility.

**Describe alternatives you've considered**
The alternative is to setup this up as custom sidekick extension as customer's Franklin repository level.

**Additional context**
Please see related discussion in this issue https://github.com/hlxsites/franklin-assets-selector/issues/34

**Comment by sdmcraft** [comment]
Copying @rofe .

**Comment by rofe** [comment]
Which 5 projects are already using this feature?

**Comment by sdmcraft** [comment]
> Which 5 projects are already using this feature?

I don't think we have those yet. Though I know a couple of instances where this has been asked for and implemented on a branch for evaluation:
- https://github.com/hlxsites/sunstar-engineering/tree/aem-assets
- https://github.com/hlxsites/takeda-ihs/tree/aem-assets

**Comment by rofe** [comment]
Then let's continue to add the button on the project side until we have usage and understand it.

**Comment by sdmcraft** [comment]
Coming back to this issue after a while. The asst selector addon is currently being used by the following customer:

1. Alshaya
2. Stewart
3. Evident Scientific
4. Volvo
5. Sunstar
6. Pet Health
7. Godrej, Maruti (Plan to use but not yet live)

@rofe , do you think we should consider adding the assets button to the sidekick by default?

**Comment by rofe** [comment]
@sdmcraft please do not post any customer names or data in public github issues. I edited your post to hide customer names.

Looking at last month's data, I can only find moderate usage from the one of the customers you mentioned above. I don't think this even justifies removing the EAT banner from the doc page, let alone adding it as a standard sidekick feature at this point.

Having the plugin configured in customer projects and customers putting it to use are different things. When I said usage above, I meant the latter.
