### ISSUE TITLE
[pt-BR],[zh-TW],[zh-CH],[ko-KR] Unlocalized string in "Help turned off" dialog in Google Drive

### ISSUE THREAD

**Issue by vintix** [adobe/helix-sidekick-extension#524]
**Description**
 Unlocalized string in "Help turned off" dialog in Google Drive [pt-BR],[zh-TW],[zh-CH],[ko-KR]

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to any Google Drive folder
3. Right Click on extension icon > Add this project
4. Right Click on extension icon > Options
5. Click on "Adavanced" string > click on "Uncheck all" button
6. Go to Google Drive folder > Select any Google Docs type file 
7. Click "Preview" button from navigation bar > Open URL
8. Click "Edit"  > Open dropdown menu on "Close" button > Click "Never show any help topics"

**Expected behavior**
String is localized:
Help turned off. You can turn it back on under Options > User experience.

**Screenshots**
<img width="1665" alt="unlocalized_string_help_1 jpg" src="https://github.com/adobe/helix-sidekick-extension/assets/24693505/216f49c9-b16d-4eda-a126-961f2e2421dc">

**Additional context**
Strings are localized in Aladdin

**String ID**
Help turned off. You can turn it back on on under Options > User experience. - help_opt_out_alert#message

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is not reproduce please observe attachment screenshot
![CHS](https://github.com/adobe/helix-sidekick-extension/assets/144205585/7dd28aea-0f1d-4c27-9c87-2b4e285e8f44)
![CHT](https://github.com/adobe/helix-sidekick-extension/assets/144205585/1b609d27-fc59-4a08-b219-db4d97d73c3c)
![PTB](https://github.com/adobe/helix-sidekick-extension/assets/144205585/ead0c8aa-1f4c-413e-89c9-375c6ef1d800)
