### ISSUE TITLE
Unlocalized string, dialogs, menus, errors, tooltips, tabs in [ko_KR] locale

### ISSUE THREAD

**Issue by vintix** [adobe/helix-sidekick-extension#527]
**Description**
Unlocalized lines, dialogs, menus, errors, tooltips, tabs in [ko-KR] locale in Google Drive

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to any Google Drive folder
3. Right Click on extension icon > Add this project
4. Select any file > Follow each button
5. See unlocalized strings

 
**Expected behavior**
Interface is localized in ko-KR

**Screenshots**
![unlocalized_strings_6](https://github.com/adobe/helix-sidekick-extension/assets/24693505/9529819e-5472-4cf8-80d7-50ab09ea1728)
![unlocalized_strings_3](https://github.com/adobe/helix-sidekick-extension/assets/24693505/c23e7484-c0b8-4c89-a421-54262e8c2630)
![unlocalized_strings_4](https://github.com/adobe/helix-sidekick-extension/assets/24693505/629c355a-6b73-4468-bba5-d74866a926fe)
![unlocalized_strings_5](https://github.com/adobe/helix-sidekick-extension/assets/24693505/93cf6c75-c000-4cdc-a874-b0cc08b624fb)

**Additional context**
Strings are localized in Aladdin.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is no longer reproducible, verified on 2023.11
![ko_kr safari](https://github.com/adobe/helix-sidekick-extension/assets/144205585/b7fe9813-5e27-4f79-8b11-5e37b8deb99e)
![ko_kr_mac_chrome](https://github.com/adobe/helix-sidekick-extension/assets/144205585/b19ab1c7-2928-4e9f-b306-c051da49cb55)
![ko_kr_mac_chrome2](https://github.com/adobe/helix-sidekick-extension/assets/144205585/79de36d9-0fa2-450c-95dd-ec32747c385e)
![ko_kr_win_chrome](https://github.com/adobe/helix-sidekick-extension/assets/144205585/a22482b7-b248-405c-86b3-5af67e6180f8)
![ko_kr_win_chrome2](https://github.com/adobe/helix-sidekick-extension/assets/144205585/d1e842c2-3cf6-4d2e-b3c7-092244d72599)
