### ISSUE TITLE
 [l10n]:LOC: Button "Open URL" missing on localized version extension

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#539]
**Description**
Button "Open URL" missing on localized version extension

**To Reproduce**

1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
3. Go to any Google Drive folder with some project
4. Right Click on extension icon > AEM Sidekick
5. Add "Repository URL*"
6. Add "Project Name"
7. Click "Add Project"
8. Select added project in Google Drive
9. Click "Preview" -> "OK"

**Expected behavior** An empty button will contain localized text "Open URL"
**Actual behavior** "Open URL" button is empty in localized extension

**Screenshots**
![empty_button_loc](https://github.com/adobe/helix-sidekick-extension/assets/144205585/bad95df9-a63b-40c7-a629-64f5b9b93e76)

**Additional context**
String is localized in GLaaS

**String ID**
open_url#message || Open URL || Localized

**Comment by makarovan** [comment]
Issue is no longer reproducible, verified on 6.33.0. String on ko_KR is blocked #527 
![fr_FR](https://github.com/adobe/helix-sidekick-extension/assets/90141516/221e7a7e-bb98-4813-b97e-37e3c9d62c08)
![ja_JP](https://github.com/adobe/helix-sidekick-extension/assets/90141516/c3b86f6b-9d47-46e5-abe7-12c4f09ef49c)
![pt_BR](https://github.com/adobe/helix-sidekick-extension/assets/90141516/1f78faab-b03c-4904-b865-7ac094e2f0d2)
![zh_CN](https://github.com/adobe/helix-sidekick-extension/assets/90141516/3958b87a-0d50-4d3c-ba35-f706523a57c0)
![ko_KR](https://github.com/adobe/helix-sidekick-extension/assets/90141516/42f3b5d3-4a88-4aea-8aec-bccf971ba412)
