### ISSUE TITLE
Sidekick does not show for svgs

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#547]
- Configure the Sidekick for www.hlx.live.
- Open https://www.hlx.live/media_1fcf935d07d8bef94aaadc585416ff8b99fa47193.png?width=2000&format=webply&optimize=medium -> SK shows up
- Open https://www.hlx.live/blocks/header/adobe-franklin-logo.svg -> SK does NOT show up

Expected: like other image types, SK should load for SVGs

Error logs:

![image](https://github.com/adobe/helix-sidekick-extension/assets/474200/3a669865-06d4-4362-8802-e25403f6095c)

**Comment by 3vil3mpir3** [comment]
@kptdobe https://github.com/adobe/helix-sidekick-extension/issues/457 seems to resolve this issue at the project level.
