### ISSUE TITLE
[i18n] Image with chinese characters in name cannot be previewed

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#552]
**Description**
Image with chinese characters in name cannot be previewed, "wrong path format" error appears

**To Reproduce**
1. Go to project folder
2. Click on extension button > Add this project
3. Upload file with name 它是事情行动.jpg to the folder
4. Select file > Preview > OK

**Expected behavior**
File can be successfully previewed

**Screenshots**
![chinese symbols image](https://github.com/adobe/helix-sidekick-extension/assets/90141516/0a503cd9-5deb-433d-a0e6-95daccb12a8c)

**Additional context**
Set of characters tested: 大家有天分, 它是事情行动直到您发现了是什么它。

**Comment by rofe** [comment]
That is working as designed. Only western characters, numbers and dashes are allowed in the URL.
