### ISSUE TITLE
[INTL]: Non latin symbol displayed like unicode in "Projects"

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#591]
**Description**
The non-Latin character entered appears as Unicode in the "Production Hostname (optional)" and "Repository URL: https://github.com/...".
**To Reproduce**

1. Go to project folder
2. Click on extension button > "Add this project"
3. Click on extension button -> "Options"
4. Click "Edit" button in "Projects"
5. Enter non latin symbol example "繁" in "Production Hostname (optional)" or "Repository URL: https://github.com/..."
6. Click "Save"
7. Observe "Production"

Observe result: Non latin symbol displayed unicode not a symbol
Expected result: All symbol displayed correctly

https://github.com/adobe/helix-sidekick-extension/assets/144205585/929d48f7-57fe-493a-b57f-be39e2b27e7f

**Comment by asthabh23** [comment]
As discussed with @rofe , closing this issue based on below key points:

Regarding point 5 in the issue explained above (Enter non latin symbol example "繁" in "Production Hostname (optional)" or "Repository URL: https://github.com/...")

1. Invalid GitHub URL is now handled in #662 
2. Non latin symbols shouldn't be allowed in Production Hostname - The domain names should be limited to characters allowed by http spec.
3. Project names anyhow can contain any unicode character. This is tested and works as expected (screenshot attached below)

<img width="799" alt="Screenshot 2024-01-31 at 12 32 33 PM" src="https://github.com/adobe/helix-sidekick-extension/assets/76686725/0c755102-52c2-441b-abb6-4fe1efc3f19c">

**Comment by asthabh23** [comment]
reopening the issue to track the validation check fix for non-latin symbols
