### ISSUE TITLE
[l10n] Safari: Strings are unlocalized in pt_BR, zh_CN, zh_TW locales

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#592]
**Description**
Strings are unlocalized in in pt_BR, zh_CN, zh_TW locales in Safari browser

**To Reproduce**
1. Install Sidekick extension https://apps.apple.com/ch/app/aem-sidekick/id1605191569?l=en&mt=12
2. Launch Safari browser
3. Right click on extension button > Manage Extension > Options

**Expected behavior**
All strings are localized

**Screenshots**
![pt_br](https://github.com/adobe/helix-sidekick-extension/assets/90141516/75cf603f-ae21-427c-a013-a358aa1fcd26)
![zh_cn](https://github.com/adobe/helix-sidekick-extension/assets/90141516/90c18a33-f3fb-4743-85df-49c492764e5b)
![zh_tw](https://github.com/adobe/helix-sidekick-extension/assets/90141516/78846145-8204-4204-836c-b65ea80474c6)

**Additional context**
Issue is not reproducible on ko_KR

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
@rofe  Issue is not fixed, verified on Safari v6.40.3
![chs safari options unloc](https://github.com/adobe/helix-sidekick-extension/assets/144205585/f8c78c3b-267b-4690-95a4-46e0ef52a0ce)
![cht safari options unloc](https://github.com/adobe/helix-sidekick-extension/assets/144205585/cbd66ff7-fc90-4a6a-9212-6c85eabc9bda)
![ptb safari options unloc](https://github.com/adobe/helix-sidekick-extension/assets/144205585/6089fe32-b8c7-49e8-95f5-d5a246a17685)
