### ISSUE TITLE
Safari: Extension action bar does not open

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#593]
**Description**
Extension action bar does not open in Safari browser

**To Reproduce**
1. Install Sidekick extension https://apps.apple.com/ch/app/aem-sidekick/id1605191569?l=en&mt=12
2. Launch Safari browser
3. Go to project folder
4. Select any file
5. Left click on extension button

**Expected behavior**
Extension action bar with opens

**Screenshots**
https://github.com/adobe/helix-sidekick-extension/assets/90141516/8a7f610e-a6db-44d5-8dd8-4f6278dd8026

**Comment by rofe** [comment]
How should the sidekick know when to open the toolbar? You need to first add a project via extension settings.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is reproducible if project was added first. Please refer to the attached video.
