### ISSUE TITLE
[INTL] Mixed character don't displayed  in "Projects"

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#595]
**Description**
Mixed character don't displayed  in "Production Hostname (optional)" or "Repository URL: https://github.com/..."
**To Reproduce**

1. Go to project folder
2. Click on extension button > "Add this project"
3. Click on extension button -> "Options"
4. Click "Edit" button in "Projects"
5. Enter mix character example "ไทยعربى国ñ" in "Production Hostname (optional)" or "Repository URL: https://github.com/..."
6. Click "Save"
7. Observe "Production"
**Observe result:** Mixed character don't displayed in "Projects"
**Expected result:** All symbol displayed correctly

https://github.com/adobe/helix-sidekick-extension/assets/144205585/c4195b74-8c91-42bc-97c5-88a9335c4cef

**Comment by asthabh23** [comment]
As discussed with @rofe , closing this issue based on below key points:

Regarding point 5 in the issue explained above (Enter mix character example "ไทยعربى国ñ" in "Production Hostname (optional)" or "Repository URL: https://github.com/...")

1. Invalid GitHub URL is now handled in #662 
2. Mix characters shouldn't be allowed in Production Hostname - The domain names should be limited to characters allowed by http spec.
