### ISSUE TITLE
Extra project is created in Options

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#596]
**Description**
When user clears and types new text in Repository URL field, extra project is created

**To Reproduce**
1. Add project to Sidekick
2. Click on extension button > Options
3. Edit project
4. Clear "Repository URL" field and type "test"
5. Save project

**Expected behavior**
Extra project is not created when user edits Repository URL

**Screenshots**
https://github.com/adobe/helix-sidekick-extension/assets/90141516/379b2891-e4f3-44a3-9a12-9646194df6ed

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is fixed, error message appears when Repository URL is cleared
https://github.com/adobe/helix-sidekick-extension/assets/144205585/3e1cd9cf-092f-4c55-95d7-749b10787f92
