### ISSUE TITLE
package.json engines - what node/npm version(s) should I use?

### ISSUE THREAD

**Issue by pzrq** [adobe/helix-sidekick-extension#601]
## Overview
The `npm` docs allow the [package.json file to contain an engines][npm-package-json-engines] field. What, if anything should go there?

## Details
From the [.circleci/config.yml][circleci-config] I might guess:

```
{
  "engines": {
    "node": ">=18"
  }
}
```

Plus it's a [currently maintained LTS][node-lts], though that says nothing about `npm` and further:

> [In the face of ambiguity, refuse the temptation to guess.](https://peps.python.org/pep-0020/)

## Proposed Actions

Populate the [package.json][gh-helix-package-json] file, `engines` field with any supported `node` or `npm` engines, thanks in advance!

[circleci-config]: https://github.com/adobe/helix-sidekick-extension/blob/fcd9dfa3046ab50e15771bb79b529e0f4d600b51/.circleci/config.yml#L5C22-L5C22
[gh-helix-package-json]: https://github.com/adobe/helix-sidekick-extension/blob/main/package.json
[node-lts]: https://github.com/nodejs/Release#readme
[npm-package-json-engines]: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

**Comment by rofe** [comment]
Thank you, but since this is not a node application, this is not applicable here.
