### ISSUE TITLE
No publish buttons visible

### ISSUE THREAD

**Issue by AntonEvers** [adobe/helix-sidekick-extension#604]
**Description**
Hi there! I am following https://www.aem.live/developer/tutorial to test the Google Drive integration. However, the publish/preview button bar is not showing up in Google Drive. I followed all the steps.

**To Reproduce**
1. Install the sidekick extension
2. Add google drive directory with example content to fstab
3. Go to the my github AEM boilerplate project and add the project to sidekick
4. Edit the homepage file in Google Drive
5. Select files in Google Drive

**Expected behavior**
The bar with publish buttons is expected like here:
![image](https://github.com/adobe/helix-sidekick-extension/assets/1489129/c7b87068-b46e-4d9f-b4d8-33426ba8869b)

Actually, I do not see any bar with buttons:
![Screenshot 2023-11-17 at 10 12 50](https://github.com/adobe/helix-sidekick-extension/assets/1489129/e94a20b2-1abc-4d0b-b02d-0275592c83d7)

**Screenshots**
I have created a screen share of the full process.
This includes version numbers.

- Google Chrome Version 117.0.5938.132 (Official Build) (arm64)
- AEM Sidekick 6.35.2

I tried the same on Brave browser version 1.59.120 Chromium: 118.0.5993.88 (Official Build) (arm64)
Here I have the exact same issue.

https://youtu.be/eGJgam86ii8

**Additional context**

**Comment by rofe** [comment]
@AntonEvers did you share your root folder with the _AEM Content Integration_ user (helix@adobe.com)? It looks like it doesn't have access...

<img width="834" alt="image" src="https://github.com/adobe/helix-sidekick-extension/assets/1609742/349fda48-1080-415e-845e-8cb75e3e2a0a">

**Comment by AntonEvers** [comment]
😢 I missed that step, but it is indeed clearly in the tutorial.
Thank you for pointing that out to me.
