### ISSUE TITLE
Incorrect display of a large number of selected assets in SharePoint

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#612]
**Description**
If you upload in a large number of assets and select them, extension will display an incorrect number of selected assets.

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
2. Go to project folder in SharePoint
3. Right Click on extension icon > Add this project
4. Left click on extension icon
5. Upload more than 100+ assets 
6. Select uploaded assets

**Expected behavior**
Correct display of selected assets 

**Screenshots**
![incorrect_display_selected_assets_1](https://github.com/adobe/helix-sidekick-extension/assets/144205585/898a3691-79a2-40c4-b725-a98bcdc9f515)

**Comment by rofe** [comment]
This is already reported in #228
