### ISSUE TITLE
Timeout error appears on sign in in Safari

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#613]
**Description**
Timeout error appears on sign in in Safari. Issue is not reproducible on Chrome

**To Reproduce**
1. Install AEM sidekick extension to Safari
2. Go to project folder in Google Drive
3. Right Click on extension icon > Add this project
4. Open extension action bar > click on profile icon > sign in
5. Sign in into account

**Expected behavior**
User signs in successfully. 

**Screenshots**
https://github.com/adobe/helix-sidekick-extension/assets/144205585/e8e2713a-7f50-4b92-b617-4b01a26c302b

**Comment by rofe** [comment]
Safari does not allow extensions to modify request headers, so it cannot use header based authentication. Until Apple implements the corresponding browser API, the fallback is cookie-based authentication, which will (inconveniently so) require users to allow 3rd party cookies (cross-site tracking).
<img width="342" alt="image" src="https://github.com/adobe/helix-sidekick-extension/assets/1609742/665483a5-33b2-41bb-a690-f559a8fb4fc1">
