### ISSUE TITLE
[i18n] CHS Strings show up instead on CHT strings

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#622]
**Description**
CHS Strings show up instead on CHT strings in Helix UI

**To Reproduce**
1. Change browser locale to Chinese (Traditional)
2. Install Helix extension
3. Go to GDrive folder > open Helix menu > Add this project
4. Click on Sign in button, observe
5. Select 2 files > Copy URLs > Preview, observe

**Expected behavior**
CHT Strings appear on CHT locale

**Screenshots**
![chinese locales](https://github.com/adobe/helix-sidekick-extension/assets/144205585/046708bc-6168-446a-8028-c2a2c2174c8e)
![copied_urls#message](https://github.com/adobe/helix-sidekick-extension/assets/144205585/c61bd2e7-74b8-405f-9a33-29bc4dbd84ea)
![user_login#message](https://github.com/adobe/helix-sidekick-extension/assets/144205585/ca82bbc1-a594-49b6-9aa1-ca6d5705558f)

**Some affected strings:**
| String ID | ENU |
| ------------- | ------------- |
| copied_urls#message | URLs copied to clipboard. |
| user_login#message | Sign in |
| help_acknowledge#message | Got it! |
| bulk_result_publish_single_failure#message | Failed to publish 1 file: |
| copy_prod_urls#message | Copy Production URLs |

**Comment by rofe** [comment]
@Adobe-G11N-I18N-L10N-Team Thanks for confirming. The language resolution seems to work as expected, but I suspect we may have mixed up the two chinese variants in the dictionary. Could you please help me clarify if the strings in these 2 files match the expected output based on the locale:
- [zh-CN](https://github.com/adobe/helix-sidekick-extension/blob/main/src/extension/_locales/zh_CN/messages.json)
- [zh-TW](https://github.com/adobe/helix-sidekick-extension/blob/main/src/extension/_locales/zh_TW/messages.json)

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
@rofe Checked the dictionaries, they are consistent with Aladdin

**Comment by lio88257** [comment]
Hi @rofe, I'm the linguist who reported the issue. I confirm that the strings in zh-CN are simplified Chinese and those in zh-TW are traditional Chinese.

**Comment by rofe** [comment]
Thanks! So the language resolution is indeed wrong :)

**Comment by rofe** [comment]
Fixed with #627 (v 6.38.2)

@Adobe-G11N-I18N-L10N-Team could you please reverify?

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is fixed, verified on Mac+Chrome and Win+Chrome. 
![zh_tw2](https://github.com/adobe/helix-sidekick-extension/assets/144205585/76c5d892-7005-4494-8586-79770d8ad424)
![zh_tw_1](https://github.com/adobe/helix-sidekick-extension/assets/144205585/f61d96d0-5755-42f1-bc66-f91abee2f5cd)
