### ISSUE TITLE
[RUM] view document source never sends data

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#628]
This is due to a (swallowed) error in `rum.js`:
```
TypeError: Cannot read properties of undefined (reading 'location')
    at sampleRUM (rum.js:41:42)
    at load (ui.js:243:3)
```
Reason: `sampleRUM` was extracted "as is" from `module.js`, but still assumes it is being run in the same window as the sidekick, and that a `window.hlx.sidekick` is present. View document source lives in a different context though, and also doesn't need the sidekick to be loaded in order to work.

Solution: either refactor `sampleRUM` to make it work independently of `window.hlx.sidekick`, or inject the `sampleRUM` call into the tab using `chrome.tabs.executeScript`.

**Comment by kptdobe** [comment]
I just looked at it, not so trivial in the end if we want to make it right. A simple fix would be to create a dummy config: 

```
window.hlx = {
    sidekick: {
      location: new URL(tab.url),
    },
  };
```

Now... this will generate a new "rum id" each time someone look at a document source, not re-using the Sidekick one. Which is anyway different from the current page one. Also if the sidekick is not open, user can still make "View Document source", i.e. no id has been generated yet for the sk. We could generate one in that case but if we want to use the same, the transfer has to be bi-directional. Probably overkill for the few usage.
