### ISSUE TITLE
Preview/Publish multiple files across different levels of the content directory

### ISSUE THREAD

**Issue by 3vil3mpir3** [adobe/helix-sidekick-extension#635]
As n author in at the content drive, I would like to navigate through several directories (e.g. pages at sitecontent root, then also assets in a separate directory) to publish/preview multiple items at the same time, almost like a "Cart" of items to publish where sidekick remembers my selections at the drive level between folders. 

Currently, while in the content drive, if I navigate away from a directory the sidekick forgets my selection in the prior directory. 

Use case:  previewing/publishing a page in root, but also several relational assets at the same time.

**Comment by rofe** [comment]
No confirmed customer need.
