### ISSUE TITLE
Sidekick login issue - errant "preview" buttons shown when nothing has been selected

### ISSUE THREAD

**Issue by 3vil3mpir3** [adobe/helix-sidekick-extension#638]
**Description**
If a user logs into the sidekick from inside a doc (e.g. the user was sent a link, or if they navigate directly to a document prior to logging in), once they navigate back to the document repo from the doc, the sidekick gives the user preview/publish options when no document has been selected.

In short: when users sign in on Sidekick’s drive view in a lower directory other than root, users don’t get the expected select files below option, instead user gets a preview option of the site itself and this doesn’t change

**To Reproduce**
Steps to reproduce the behavior (tested only in Sharepoint, unknown if this is also an issue in GD):
1. In non-logged in state: navigate through content directory into a document
2. Open document, login
3. Navigate back to the content drive from the document
4. See sidekick is displaying preview button even though no documents have been selected.  
5. Refreshing or navigating up a level in to content directory resolves this issue 

Video of behavior below

https://github.com/adobe/helix-sidekick-extension/assets/2037906/01b74942-31e6-4b7a-befb-e23dfd07be68

**Comment by rofe** [comment]
Looks like the sidekick isn't picking up the URL change if the user is coming to the folder view from a document.
