### ISSUE TITLE
[i18n] Unlocalized string in "Advanced" settings in "Edit" Project

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#640]
**Description**
Unlocalized string in "Advanced" settings in "Edit" Project
**To Reproduce**

1. Install Sidekick extension
2. Go to Google Drive project folder
3. Add Project
4. Go to options
5. Go to "Advanced" in left nav menu
6. Click "Edit" project button

**Expected behavior**
Strings is localized: "Helix 5 (experimental)"
**Actual result**
String is unlocalized
**Additional context**
String is not present in Aladdin.
**Screenshot**
![helix_sidekick_ja_JP_unloc](https://github.com/adobe/helix-sidekick-extension/assets/144205585/132c205f-addc-4327-89ce-fb3f2529a52f)

**Comment by rofe** [comment]
> String is not present in Aladdin.
@Adobe-G11N-I18N-L10N-Team No need to report issues like that. The current process is for automation to pick up new English strings, have them translated and add translation via pull request.
cc @rgeraghty
