### ISSUE TITLE
[i18n] "Preview generated" dialog appears on preview files with non-latin characters in name

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#651]
**Description**
"Preview generated" dialog appears on preview Excel/Word/Google Sheets files with only non-latin characters in name 

**To Reproduce**
1. Install Sidekick extension
2. Add project 
3. Select file with only non-latin characters in name - Google Table for GDrive, Word/Excel for Sharepoint
4. Click on Preview > OK

**Expected behavior**
"Failed to generate preview" dialog appears on trying to preview files with only non-latin characters in filename

**Screenshots**
![file preview gdrive](https://github.com/adobe/helix-sidekick-extension/assets/144205585/ecc486f9-fe17-4207-b171-7e44c13b8f1d)
![file preview sharepoint](https://github.com/adobe/helix-sidekick-extension/assets/144205585/2001f153-2d3a-4d7d-b565-e4c9bb33ab07)

**Additional context**
Issue does not appear with preview of Google Doc file

**Comment by rofe** [comment]
This works as expected: non-latin characters in filenames are being converted to the supported range of characters. If you press the "copy RUL" button, you will see the resulting path from your filename.
