### ISSUE TITLE
The URL gets trunctated when there is a comma in the document filename when the copy URL function is used

### ISSUE THREAD

**Issue by michaelktiufb** [adobe/helix-sidekick-extension#658]
**Description**
When you are in SharePoint and open Sidekick, there is a copy URL function that appears when a file is selected. It works fine EXCEPT when the document name contains a comma

**To Reproduce**
 Upload any document in SharePoint with a filename that has a comma e.g "this,is a test.dox"
2. Open Sidekick, log in and select the document
3. In SharePoint select the file and click the "Copy URL" function (preview or live)
4. Check the copied URL

**Expected behavior**
Complete URL path is returned

**Actual behavior**
URL was truncated on the part where the comma is "e.g. https://somedomain.com/drafts/this
instead of https://somedomain.com/drafts/this-is-a-test

**Screenshots**

**Additional context**
Business impact: Users would have to manually construct the URL in preview or publish mode which is not easy for neophyte users

**Comment by felix-staud** [comment]
The same issue occurs with a `.` in the filename
