### ISSUE TITLE
Bulk operations don't work on Sharepoint list urls without `RootFolder`

### ISSUE THREAD

**Issue by dylandepass** [adobe/helix-sidekick-extension#675]
**Description**
If a sharepoint directory url doesn't have a `RootFolder` search param then bulk operations will not work.

**Work Around**
1. Open a document
2. Navigate back to the list view by clicking on the file name

![screenshot_2024-02-23_at_11 55 25___am](https://github.com/adobe/helix-sidekick-extension/assets/3231084/74699b6c-e6db-43c6-b226-e141d22f7fa2)

Bulk Operations should then work

**Comment by rofe** [comment]
Another workaround (best practice?) would be to create a dedicated website root folder inside shared documents and use it as the mountpoint.
