### ISSUE TITLE
Extra project created after editing repository name in Repository URL in Options

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#687]
**Description**
When user edits repository name in Repository URL, extra project with new preview link is created

**To Reproduce**
1. Add project to Sidekick
2. Click on extension button > Options
3. Edit project
4. In Repository URL field type some characters in repository name part (https://github.com/owner/repository/tree/main -> https://github.com/owner/repositoryTEST/tree/main)
5. Save project

**Expected behavior**
Extra project is not created when user edits repository name in Repository URL

**Screenshots**
https://github.com/adobe/helix-sidekick-extension/assets/144205585/8b74954a-f983-4016-bb2b-322171ee7c4b

**Comment by rofe** [comment]
This was fixed by @asthabh23 in #596. No longer reproducible in v6.41.0.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
@rofe Issue is different from #596. Extra project is created when repo url is edited, not completely cleared. Verified on 6.41.0

https://github.com/adobe/helix-sidekick-extension/assets/144205585/849fe432-69f3-45c2-9470-2cffbdedcde5
