### ISSUE TITLE
Unlocalised string "Invalid hostname" in Options > Edit

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#700]
**Description**
String "Invalid hostname" is unlocalized

**To Reproduce**
1. Install AEM sidekick extension
2. Go to project folder in Google Drive
3. Click on extension button > "Add this project"
4. Right click on extension button -> "Options"
5. Click "Edit" button in "Projects"
6. Enter "1" character in "Production Hostname (optional)"

**Expected behavior**
String is localized

**Additional context**
String is localized in GLaaS
String ID: config_invalid_host#message

**Screenshots**
![6 41 1 fra](https://github.com/adobe/helix-sidekick-extension/assets/144205585/c029f917-138e-4d06-b12e-698191d0e7da)
![6 41 1 jpn](https://github.com/adobe/helix-sidekick-extension/assets/144205585/efcbc0bd-dbe1-4614-94aa-33770cb7b92b)

**Comment by rgeraghty** [comment]
@rofe fix is part of PR https://github.com/adobe/helix-sidekick-extension/pull/706/files

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is still reproduce
![700_strill_repro_ja_JP](https://github.com/adobe/helix-sidekick-extension/assets/144205585/14e18237-f22f-47c8-ac7c-8f14d8d48f68)

**Comment by rofe** [comment]
@Adobe-G11N-I18N-L10N-Team that's because the issue is still **open**.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is no longer reproduce
![700_fixed_ja_JP](https://github.com/adobe/helix-sidekick-extension/assets/144205585/8490d7d9-24e2-4e30-8598-ab646d223e38)
