### ISSUE TITLE
file selection only works if sharepoint is english

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick-extension#711]
The bulk selection doesn't work if the language is anything but English.

**Comment by rofe** [comment]
@stefanseifert

**Comment by stefanseifert** [comment]
no selection at all is detected in folder view when the sharpoint display language is set to german.

i had a hard time figuring out how to actually change the language of sharepoint - this documentation article describes it https://support.microsoft.com/en-US/office/change-sharepoint-online-language-settings-0f6a477a-dcab-4462-9d0c-e3b53d138183 - but fails to point out the correct starting point. there is not direct link to the "office profile" any longer. in the microsoft account there is a possibility to change the display language, but this does not affect sharepoint and other office browser app.s

this is the way i found to change the language:
1. go to "my microsoft 365 profile"
2. go to "update profile"
3. in the "update your profile" view there is a link, "how can i change language and regional settings" - expand it and click on "here"
4. now you are in the office profile, and behind the ellipsis (...) there is a link "language and region" where you can change the display language
5. the change does not get into effect immediately - you have to wait 5-10min for this
