### ISSUE TITLE
Unable to select files to publish from Google Drive

### ISSUE THREAD

**Issue by leachuk** [adobe/helix-sidekick-extension#724]
**Description**
I'm attempting to select documents for publishing in the sidekick, following the tutorial at https://www.aem.live/developer/tutorial

The extension is installed and active. When documents are selected in Google Drive, they are not reflected in the Sidekick toolbar. It maintains the message "Select files below"

**To Reproduce**
Following the steps in the tutorial at https://www.aem.live/developer/tutorial

I've tried this in Chrome, Chrome Incognito and Safari. I've also tried with the bookmarklet by using https://www.aem.live/tools/sidekick/  The broken behaviour is consistent, so I do not believe there is some other extension or browser setting causing this (of course it's difficult to be 100% sure of this as there are no error messages provided)

**Expected behavior**
I can use the Sidekick to select documents from my Google Drive to publish, as described in https://www.aem.live/developer/tutorial

**Screenshots**
![Screenshot 2024-05-02 at 10 27 31 AM](https://github.com/adobe/aem-sidekick/assets/4289596/99af5df2-563c-4c56-a681-dbc9c2289140)

**Additional context**
I'd love to provide logs if someone can tell me where to grab them from. I'm not familiar with extension dev.

**Comment by rofe** [comment]
@leachuk Thanks for reporting! I suspect a DOM change in Google Drive. Looking into it now...

**Comment by leachuk** [comment]
Confirmed it's working with the latest version from the Chrome store.

Thanks for the quick turnaround 🥳
