### ISSUE TITLE
[l10n] Unlocalized "Authorization Token (optional)" string in Options > Advanced

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#764]
**Description**
"Authorization Token (optional)" string is unlocalized in Options > Advanced

**To Reproduce**
1. Install AEM Sidekick extension
2. Go to project folder
3. Right click on extension > Add this project
4. Right click on extension > Options 
5. Click on "Advanced" button
5. Click on "Edit" button near added project

**Expected behavior**
String is localized

**Screenshots**
![6 45 5 deu](https://github.com/adobe/helix-sidekick-extension/assets/144205585/931df789-3808-4e16-8385-a08970010e1a)
![6 45 5 jpn](https://github.com/adobe/helix-sidekick-extension/assets/144205585/26bb27fd-9827-46d8-b533-8da7d9b2f8ab)

**Additional context**
String is localized in GLaaS.
String ID - config_manual_authorizationToken_placeholder#message
String - Authorization Token (optional)

**Comment by rofe** [comment]
@rgeraghty can you take this?

**Comment by rgeraghty** [comment]
Hi @rofe please merge https://github.com/adobe/helix-sidekick-extension/pull/765 to translate this string,

**Comment by rgeraghty** [comment]
Translations merged,

**Comment by rofe** [comment]
Will be fixed in v6.45.6

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
No longer reproducible, verified on v6.45.0

![#764_fixed](https://github.com/adobe/helix-sidekick-extension/assets/144205585/390e51a9-436b-49e7-bbd7-5c908ea7a4af)
