### ISSUE TITLE
Document can be previewed and published without adding project to Sidekick

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-sidekick-extension#838]
**Description**
Preview, Publish, Copy URL buttons are active on action bar when project is not added to Sidekick

**To Reproduce**
1. Install extension
2. Go to project folder
3. Click on extension button to show action bar
4. Select document

**Expected behavior**
Preview, Publish, Copy URL buttons are not available when project is not added to Sidekick

**Screenshots**
![6 49 4](https://github.com/user-attachments/assets/e559bf5a-2616-402e-b8be-61af41e5d5d0)

**Comment by rofe** [comment]
This is a feature ("transient mode"). If you want to prevent this from happening, you need to enable [authentication for authors](https://www.aem.live/docs/authentication-setup-authoring).
